apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperatura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversaotemperatura
  template:
    metadata:
      labels:
        app: conversaotemperatura
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"  # Porta onde sua aplicação expõe as métricas
        prometheus.io/path: "/metrics"  # Opcional — default é /metrics
    spec:
      containers:
      - name: conversao
        image: luuucasmoreia/conversao-temperatura:v1
        ports:
         - name: http
           protocol: TCP
           containerPort: 8080
