apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperatura
spec:
  replicas: 4
  selector:
    matchLabels:
      app: conversaotemperatura
  template:
    metadata:
      labels:
        app: conversaotemperatura
    spec:
      containers:
      - name: conversao
        image: luuucasmoreia/conversao-temperatura:v1
        ports:
         - name: http
           protocol: TCP
           containerPort: 8080
