apiVersion: v1
kind: Service
metadata:
  name: conversaotemperatura
spec:
  selector:
    app: conversaotemperatura
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
    nodePort: 30000
  type: NodePort